### PR TITLE
minor tweaks

### PR DESCRIPTION
**Pull request by josephwb**
1. Adds worms and irmng to `make clean`.
2. Silences warning: `Note: Some input files use unchecked or unsafe operations.`

I've made ott after making these changes, so I think things are fine. I should note, though, that it was not possible to build ott on the non-master branch, as `make` would switch me back to master. I think this is the culprit:
```
...
chmod +x bin/jython
(cd feed/amendments/amendments-1; git checkout master)
/bin/sh: 1: cd: can't cd to feed/amendments/amendments-1
Switched to branch 'master'   <-----
Your branch is ahead of 'origin/master' by 2 commits.
  (use "git push" to publish your local commits)
(cd feed/amendments/amendments-1; git pull)
/bin/sh: 1: cd: can't cd to feed/amendments/amendments-1
Already up-to-date.
(cd feed/amendments/amendments-1; git checkout -q `cat ../../../feed/amendments/refspec`)
/bin/sh: 1: cd: can't cd to feed/amendments/amendments-1
cat: ../../../feed/amendments/refspec: No such file or directory
...
```
So I made ott by going to "master" and pulling from "makeclean".

### CODE REVIEW

**Comment by josephwb** [comment]
Update: I added an amendments dependency so the problem above should not happen.

**Comment by jar398** [comment]
You know you will end up with ids that are not real OTT ids, if you just do
'make ott'. They will not be in what's in OTT 2.10 (unless you change
prev_ott to 2.10), they will be in the 'fake' 9000000+ range, and they will
get reused in other builds.

What is your purpose in doing this? It is easy to just download 2.10, and
if you re-make you won't get 2.10 (or anything else in particular). Are you
doing development on the taxonomy?

**Comment by jar398** [comment]
The 'master' branch you see mentioned above is the master branch of the amendments-1 repo, not the reference-taxonomy repo. Your statement 'make would switch me back to master' is mistaken. I *never* build taxonomies from the master branch and the 'make' rules do not change the git HEAD for the reference-taxonomy clone.

**Comment by josephwb** [comment]
If you look at the log, it tries to cd into amendments, but fails because it does not exist, so the subsequent `checkout master` applies to "reference-taxonomy", not "amendments".

**Comment by jar398** [comment]
It would help if the semicolons were turned into &&  (i.e. it should only do 'git checkout' if the 'cd' succeeds; and if it fails the 'make' will fail).

**Comment by jar398** [comment]
What is your purpose in building the taxonomy? Not that there is anything wrong with it, but I wonder if maybe you mean to be doing something else, or have false expectations. It is easy to just download 2.10, and if you re-make you won't get 2.10 (or anything else in particular). Are you doing development on the taxonomy?

**Comment by josephwb** [comment]
No purpose; I noticed weird things so tried to remedy them. Feel free to disregard.

**Comment by jar398** [comment]
Yes, but (a) you fixed this by adding the dependency, so now the directory
gets created, (b) if the rules said "(cd ... && git ...)" instead of "(cd
...; git ...)" then the failure would have been much quicker and more
evident.

**Comment by jar398** [comment]
Related: #236

**Comment by josephwb** [comment]
I don't follow. Isn't not-failing better than a quick-fail?

I don't know how you haven't encountered this problem before: make clean gets rid of the amendments, so any make after that should fail.

**Comment by josephwb** [comment]
BTW I do not claim any of this to be "better" (or even "good"), it was a quick hack to identify a problem. It should probably instead check for the existence of the directory, and update it if present or clone it if not.

**Comment by jar398** [comment]
Yes, indeed, not failing *is* better than quick-fail.  If there's a failure, you want quick-fail.  If there isn't, you want not failing. Not sure why you ask. If you don't want to make the && change, I will.

Checking for existence of things and making them if they're not there is *exactly* what 'make' does. Your fix to the dependencies solves the problem, so there is nothing more to do. But as a general rule one should never use semicolon in shell commands, ever. && should be used for sequences. There are probably ways that this could fail even if the rules are correct and 'make' is working fine. But it's not worth thinking about; && is always preferable to ; even when there is no known difference in effect.

&&-over-' is in the spirit of 'The Elements of Programming Style' (which I haven't read in decades, but still find influential).

The reason I haven't encountered the problem is that I never use 'make clean' in this repo. I have never found it to be necessary.

**Comment by josephwb** [comment]
I agree with all of that.
I figured I would pass this along to you and you could edit (or ignore) as you please. The && change sounds like a good idea; I'll leave it to you.

**Comment by kcranston** [comment]
Closing without merge. @jar398 to revisit.

**Comment by jar398** [comment]
@josephwb Some of these changes have been taken care of elsewhere; the rest I'll deal with later. Thanks for working on this

**Pull request closed without merging**
