### PR TITLE
Swap Proximity heuristic to fix #304; address OTT id problem found by @hyanwong

### LINKED ISSUE #304: Handling of Diplonema in OTT3.0
There is a lot more merging of taxa in OTT3.0. Contrast v3.0:

 https://devtree.opentreeoflife.org/taxonomy/browse?name=diplonema

and

https://tree.opentreeoflife.org/taxonomy/browse?name=diplonema

The merging of genus Hybocodon (https://tree.opentreeoflife.org/taxonomy/browse?id=4717850) into diplonema (excavata) in OTT3.0 is problematic in that it results in Metazoa not being monophyletic in the synth tree

### PR DESCRIPTION
**Pull request by jar398**
Please merge the other PRs first.

This PR is ready to go, and it's an open question whether to update the writeup to reflect this new version instead of draft3 (or draft3a which is identical in its statistics). Draft3 is not suitable for production use and IMO shouldn't be the version that goes into Zenodo. This version (draft4) I expect to work fine in production, but it would be good to get some vetting from @mtholder and/or @hyanwong to be sure.

The fix for #304 was trivial, although investigating the impact of the fix took a while. The Zaglossus id fix took longer, as it was actually a combination of several bugs in id assignment code written since 2.10 was deployed.

### CODE REVIEW

**Comment by kcranston** [comment]
Will updating to draft4 only affect the results section (tables, and summary stats in the text)?

**Comment by jar398** [comment]
draft5 now.  Besides the table, summary stats, and the figure that gives alignment summary stats, there is just one small change, to the description of the Proximity heuristic.

@mtholder has agreed to test draft5. Writeup changes should wait for that.

**Comment by kcranston** [comment]
OK, I am convinced about updating. Thanks for the info.

**Comment by kcranston** [comment]
Can you fix conflicts, @jar398 ?

**Pull request merged**
